kind: Pod
apiVersion: v1
metadata:
  name: googlemap
spec:
  containers:
  - name: kishore
    image: nginx
    # env:
    # - name: saibaba
    #   valueFrom:
    #     configMapKeyRef:
    #      name: firstdata           # The ConfigMap this value comes from.
    #      key: pranavi
    envFrom:
    - configMapRef:
        name: firstdata