kind: Pod
apiVersion: v1
metadata:
  name: testpodforservice
  labels:
    sudheer: "good-boy"
    project: "expense"
    environment: "dev"
    component: "testing"
spec:  
  containers:
  - name: nginx
    image: nginx