kind: Pod
apiVersion: v1
metadata:
  name: testpodforservice
  labels:
    sudheer: "good boy"
    project: "expense"
    environment: "dev"
    component: "testing"
containers:
- name: nginx
  image: nginx